name: dart_twitter_api
description: A dart wrapper for using the Twitter API with well documented interfaces for every endpoint.
version: 0.5.8
homepage: https://github.com/robertodoering/twitter_api
repository: https://github.com/robertodoering/twitter_api
issue_tracker: https://github.com/robertodoering/twitter_api/issues

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
 http: ^0.13.0
 intl: ^0.17.0
 json_annotation: ^4.0.0
 oauth1: ^2.0.0

dev_dependencies:
 flutter_test:
  sdk: flutter
 build_runner:
 json_serializable:
 mockito:
 pedantic:
 test:
